name: Release

# This workflow handles automated releases and OTA updates for the ROI Mailchimp Reporter
# It builds for both Windows and macOS, signs the artifacts, and generates a latest.json
# for automatic updates. Triggered by pushing a version tag (e.g., v1.0.83)
on:
  push:
    tags:
      - 'v*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
  TAURI_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_PRIVATE_KEY_PASSWORD }}

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install dependencies (Windows)
        if: matrix.platform == 'windows-latest'
        run: |
          rustup target add x86_64-pc-windows-msvc
          cargo install tauri-cli --version 1.5.4

      - name: Install dependencies (macOS)
        if: matrix.platform == 'macos-latest'
        run: |
          rustup target add x86_64-apple-darwin
          cargo install tauri-cli --version 1.5.4

      - name: Install project dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Build Tauri app
        run: cargo tauri build --release

      - name: Create Release
        if: matrix.platform == 'windows-latest'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            src-tauri/target/release/bundle/msi/*.msi
            src-tauri/target/release/bundle/nsis/*.exe
            src-tauri/target/release/bundle/updater/*.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release (macOS)
        if: matrix.platform == 'macos-latest'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            src-tauri/target/release/bundle/dmg/*.dmg
            src-tauri/target/release/bundle/macos/*.app
            src-tauri/target/release/bundle/updater/*.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate latest.json
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "{\"version\":\"$VERSION\",\"notes\":\"Release $VERSION\",\"pub_date\":\"$(date -u +\"%Y-%m-%dT%H:%M:%SZ\")\",\"platforms\":{\"windows\":{\"signature\":\"\",\"url\":\"https://github.com/TimVanC/roi-mailchimp-reporter/releases/download/$VERSION/roi-mailchimp-reporter_${VERSION#v}_x64-setup.msi\"},\"darwin\":{\"signature\":\"\",\"url\":\"https://github.com/TimVanC/roi-mailchimp-reporter/releases/download/$VERSION/roi-mailchimp-reporter_${VERSION#v}_x64.dmg\"}}}" > src-tauri/target/release/bundle/updater/latest.json

      - name: Sign latest.json
        run: cargo tauri signer sign -w src-tauri/target/release/bundle/updater/latest.json

      - name: Upload latest.json
        uses: softprops/action-gh-release@v1
        with:
          files: src-tauri/target/release/bundle/updater/latest.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 