name: Build and Release Tauri App

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        platform: [windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: npm install

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Build app
        run: npm run tauri build

      - name: Install Tauri signer
        run: cargo install tauri-signer

      - name: Sign artifacts
        run: |
          cargo tauri signer sign \
            --private-key "${{ secrets.TAURI_PRIVATE_KEY }}" \
            --password "${{ secrets.TAURI_PRIVATE_KEY_PASSWORD }}" \
            --bundle ./src-tauri/target/release/bundle

      - name: Generate latest.json
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "{
            \"version\": \"${VERSION#v}\",
            \"notes\": \"New release ${VERSION}\",
            \"pub_date\": \"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\",
            \"platforms\": {
              \"darwin-x86_64\": {
                \"signature\": \"$(cat ./src-tauri/target/release/bundle/macos/ROI\\ Mailchimp\\ Reporter.app.tar.gz.sig)\",
                \"url\": \"https://github.com/TimVanC/roi-mailchimp-reporter/releases/download/${VERSION}/ROI.Mailchimp.Reporter.app.tar.gz\"
              },
              \"windows-x86_64\": {
                \"signature\": \"$(cat ./src-tauri/target/release/bundle/msi/ROI\\ Mailchimp\\ Reporter_${VERSION#v}_x64_en-US.msi.sig)\",
                \"url\": \"https://github.com/TimVanC/roi-mailchimp-reporter/releases/download/${VERSION}/ROI.Mailchimp.Reporter_${VERSION#v}_x64_en-US.msi\"
              }
            }
          }" > latest.json

      - name: Upload release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            src-tauri/target/release/bundle/**/*.dmg
            src-tauri/target/release/bundle/**/*.msi
            src-tauri/target/release/bundle/**/*.tar.gz
            latest.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 